const  SERVER={
     URLAPI: 'https://edubega0707.pythonanywhere.com',  
     
}
const SAGA_USER={
    LOGIN: 'LOGIN',
    ESTABLECERSESION: 'ESTABLECERSESION',
    CERRARSESION: 'CERRARSESION',
    GETUSUARIO: 'GETUSUARIO',
    OBTENERUSUARIO: 'OBTENERUSUARIO',
}

const REVISTA = {
    GET_ARTICULOS: 'GET_ARTICULOS',
    PUT_ARTICULOS: 'PUT_ARTICULOS',
    GET_ARTICULOS_TIPO_USUARIO: "GET_ARTICULOS_TIPO_USUARIO",
    PUT_ARTICULOS_TIPO_USUARIO: "PUT_ARTICULOS_TIPO_USUARIO",
    GET_ARTICULO_DETAIL: "GET_ARTICULO_DETAIL",
    PUT_ARTICULO_DETAIL: "PUT_ARTICULO_DETAIL",
    ADD_TIPOS_USUARIO: 'ADD_TIPOS_USUARIO',
    PUT_CATEGORIAS: 'PUT_CATEGORIAS',
}


let CARTERA={
    GET_POLIZAS_USUARIO:"GET_POLIZAS_USUARIO",
    PUT_POLIZAS_USUARIO:'PUT_POLIZAS_USUARIO',

    GET_POLIZAS_USUARIO_CARTERA:'GET_POLIZAS_USUARIO_CARTERA',
    PUT_POLIZAS_USUARIO_CARTERA:'PUT_POLIZAS_USUARIO_CARTERA',

    GET_CLIENTES_USUARIO_CARTERA:'GET_CLIENTES_USUARIO_CARTERA',
    PUT_CLIENTES_USUARIO_CARTERA:'PUT_CLIENTES_USUARIO_CARTERA',

    GET_PROSPECTOS_USUARIO_CARTERA:'GET_PROSPECTOS_USUARIO_CARTERA',
    PUT_PROSPECTOS_USUARIO_CARTERA:'PUT_PROSPECTOS_USUARIO_CARTERA',

    GET_POLIZA_DETAIL:'GET_POLIZA_DETAIL',
    PUT_POLIZA_DETAIL:'PUT_POLIZA_DETAIL',
    GETRECIBOSENPOLIZA:'GETRECIBOSENPOLIZA',
    OBTENERRECIBOSENPOLIZA:'OBTENERRECIBOSENPOLIZA',
    GET_ARCHIVOS_POLIZA:'GET_ARCHIVOS_POLIZA',
    PUT_ARCHIVOS_POLIZA:'PUT_ARCHIVOS_POLIZA',
    GETOBJETOVEHICULO:"GETOBJETOVEHICULO",
    OBTENEROBJETOVEHICULO:"OBTENEROBJETOVEHICULO",


}



let CONSTANTES = Object.assign(SERVER, SAGA_USER,  REVISTA, CARTERA);

export default CONSTANTES;